Update latest vitess.io/vitess 20240215
planetscale/schemadiff pull request #18
Opened 2024-02-16 10:23 UTC by shlomi-noach

Updating `vitess.io/vitess` to latest from upstream: `v0.10.3-0.20240215220334-f82fb7cbd03d`. This specifically includes [foreign key loop resolution](https://github.com/vitessio/vitess/pull/15062).

2024-02-16 10:24 UTC, shlomi-noach commented
@dbussink for review as this introduces `vtenv`, and `go mod tidy` re-introduced many libraries which I believe were removed earlier on.

2024-02-22 15:18 UTC, dbussink requested changes

2024-02-22 15:18 UTC, dbussink commented on pkg/core/exec.go
> +		TruncateUILen:      servenv.TruncateUILen,
We should not use servenv here but provide these values ourselves. 

The defaults of 0 are actually fine and better. It also will clean up go.mod again and greatly reduce the binary size.

2024-02-22 15:26 UTC, dbussink approved these changes

2024-02-22 15:33 UTC, merged